# Generated by Django 5.1.3 on 2024-11-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_rename_create_at_project_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "التصنيف", "verbose_name_plural": "التصنيف"},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "Project", "verbose_name_plural": "Project"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Task", "verbose_name_plural": "Task"},
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.IntegerField(
                choices=[(1, "قيد التنفيذ"), (2, "مكتمل "), (3, "معلق "), (4, "ملغي ")],
                default=1,
            ),
        ),
    ]
